export const REGISTER_COMPANY = "REGISTER_COMPANY";
export const REGISTER_COMPANY_ERROR = "REGISTER_COMPANY_ERROR";

export const EMAIL_VERIFY = "EMAIL_VERIFY"
export const EMAIL_VERIFY_ERROR = "EMAIL_VERIFY_ERROR"

export const MOBILE_VERIFY = "MOBILE_VERIFY"
export const MOBILE_VERIFY_ERROR = "MOBILE_VERIFY_ERROR"

